# Generated by Django 5.0.3 on 2024-11-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_date', models.DateField(verbose_name='date_found')),
                ('note', models.CharField(max_length=100)),
                ('rough_pos', models.CharField(max_length=100)),
                ('exact_pos', models.CharField(max_length=100)),
                ('founder', models.CharField(max_length=100)),
            ],
        ),
    ]
