# Generated by Django 5.0.3 on 2024-11-11 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='exact_pos',
        ),
        migrations.RemoveField(
            model_name='item',
            name='rough_pos',
        ),
        migrations.AddField(
            model_name='item',
            name='building_found',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='item.building'),
        ),
        migrations.AddField(
            model_name='building',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.campus'),
        ),
        migrations.AddField(
            model_name='item',
            name='campus_found',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='item.campus'),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='item.item_type'),
        ),
    ]
