# Generated by Django 5.0.3 on 2024-11-14 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_building_campus_item_type_remove_item_exact_pos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='building',
            new_name='building_name',
        ),
        migrations.RenameField(
            model_name='campus',
            old_name='campus',
            new_name='campus_name',
        ),
    ]
