# Generated by Django 5.0.3 on 2024-11-14 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_rename_building_building_building_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_type',
            old_name='item_type',
            new_name='item_type_name',
        ),
    ]
