# Generated by Django 5.0.3 on 2024-11-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_rename_item_type_item_type_item_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='exact_position',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
