# Generated by Django 5.0.3 on 2024-11-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_item_exact_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stateus',
            field=models.BooleanField(default=False),
        ),
    ]
