# Generated by Django 5.0.3 on 2024-11-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_item_current_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='stateus',
            new_name='status',
        ),
    ]
