# Generated by Django 5.0.3 on 2024-11-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_alter_item_founder_alter_item_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='founder',
            field=models.CharField(max_length=100),
        ),
    ]
