# Generated by Django 5.0.3 on 2024-11-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_alter_item_founder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='exact_position',
            field=models.CharField(default='', max_length=100),
        ),
    ]
