# Generated by Django 5.0.3 on 2024-11-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_item_owner_alter_item_founder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='current_position',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='exact_position',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
