# Generated by Django 5.0.3 on 2024-11-27 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_alter_item_current_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'managed': False},
        ),
    ]
