# Generated by Django 5.0.3 on 2024-11-27 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_alter_item_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='Items',
        ),
    ]
