# Generated by Django 5.0.3 on 2024-11-27 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_alter_item_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table=None,
        ),
    ]
