# Generated by Django 5.0.3 on 2024-11-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0017_alter_item_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='img_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='img.jpg', upload_to='images')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
