# Generated by Django 5.0.3 on 2024-11-28 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0018_img_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
    ]
