# Generated by Django 5.0.3 on 2024-11-28 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0020_item_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='img_model',
        ),
    ]
