# Generated by Django 5.0.3 on 2024-12-05 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0021_delete_img_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='building',
            name='campus',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='item.campus'),
        ),
        migrations.AddField(
            model_name='building',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='item.building_type'),
        ),
    ]
