# Generated by Django 5.0.3 on 2024-12-05 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0023_alter_building_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='item.building_type'),
        ),
    ]
