# Generated by Django 5.0.3 on 2024-12-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0025_alter_building_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
