# Generated by Django 5.0.3 on 2024-12-10 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0026_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='type',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='item.building_type'),
        ),
    ]
