# Generated by Django 5.0.3 on 2024-12-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0027_alter_building_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='exact_position',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
