# Generated by Django 5.0.3 on 2024-12-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0028_alter_item_exact_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
