# Generated by Django 5.0.3 on 2024-12-10 10:48

import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_type_report_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('content', mdeditor.fields.MDTextField(blank=True, default='')),
            ],
        ),
    ]
