# Generated by Django 5.0.3 on 2024-12-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
